# Generated by Django 5.1 on 2024-08-27 19:16

import django.utils.timezone
import shortener.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_code',
            field=models.CharField(default=shortener.models.generate_shortcode, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='urlanalytics',
            name='access_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
